import { Inter, Roboto_Mono } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata = {
    title: "Profile",
    description: "Generated by create next app",
  };
  
 
export default function Layout({ children }) {
  return (
    <div className={`${inter.variable} ${roboto_mono.variable}`}>
      {children}
    </div>
  )
}